language: node_js
node_js:
  - "0.10"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - npm install
script:
  - export DISPLAY=:99
  - npm run dev & npm run test; export NODE_TEST_EXIT_CODE=$?
  - exit $NODE_TEST_EXIT_CODE
